
--create USERS TABLE MS-SQL
CREATE TABLE USERSv2 (
    USER_ID INT IDENTITY(1,1) PRIMARY KEY,
    FIRST_NAME VARCHAR(30) NOT NULL,
    LAST_NAME VARCHAR(30) NOT NULL,
    MIDDLE_NAME VARCHAR(30) NOT NULL,
    EMAIL VARCHAR(50),
    ADDRESS_LINE_1 VARCHAR(50),
    ADDRESS_LINE_2 VARCHAR(50),
    ADDRESS_LINE_3 VARCHAR(50),
    CITY VARCHAR(30),
    STATE VARCHAR(30),
    COUNTRY VARCHAR(30),
    ZIP_CODE VARCHAR(30),
    PHONE VARCHAR(30),
    CREATE_DATE DATETIME2 DEFAULT GETDATE(),
    UPDATE_DATE DATETIME2,
    STATUS CHAR(1) DEFAULT 'A'
)
--ms-sql trigger for create_date, update_date and status and user_id
CREATE TRIGGER [dbo].[TRG_USERSv2_CREATE_DATE] ON [dbo].[USERSv2]
AFTER INSERT
AS
BEGIN
SET NOCOUNT ON;
UPDATE USERSv2
SET CREATE_DATE = GETDATE()
WHERE USERS = (SELECT USERS FROM INSERTED)
END
GO



--create USERS TABLE MYSQL
CREATE TABLE USERS (
USERS INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
FIRST_NAME VARCHAR(30) NOT NULL,
LAST_NAME VARCHAR(30) NOT NULL,
MIDDLE_NAME VARCHAR(30) NOT NULL,
EMAIL VARCHAR(50),
ADDRESS_LINE_1 VARCHAR(50),
ADDRESS_LINE_2 VARCHAR(50),
ADDRESS_LINE_3 VARCHAR(50),
CITY VARCHAR(30),
STATE VARCHAR(30),
COUNTRY VARCHAR(30),
ZIP_CODE VARCHAR(30),
PHONE VARCHAR(30),
CREATE_DATE TIMESTAMP,
UPDATE_DATE TIMESTAMP,
STATUS INT(1) DEFAULT 1
)
